<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?= CONFIG_SITE_TITLE ?></title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet">
    <style>
        #caroussel img{
          width: 100%;
          aspect-ratio: 16/10;
        }

        .footer {
      position: fixed;
      width: 100%;
      left: 0;
      bottom: 0;
      color: #FFF;
      text-align: center;
      background-color: black;
    }
    </style>
</head>
<body>
<!-- HEADER -->
<header>
<nav class="navbar navbar-expand-lg bg-dark" data-bs-theme="dark">
  <div class="container-fluid">
  <a class="navbar-brand" href="?page=home">
      <img src="../uploads/avatar_1706617495.png" alt="Logo" width="30" height="24" class="d-inline-block align-text-top">
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link <?php if(isset($_GET['page']) && $_GET['page']==='home') echo "active"; ?>" aria-current="page" href="?page=home">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link <?php if(isset($_GET['page']) && $_GET['page']==='gallery') echo "active"; ?>" href="?page=gallery">Gallery</a>
        </li>
        <li class="nav-item">
          <a class="nav-link <?php if(isset($_GET['page']) && $_GET['page']==='contact') echo "active"; ?>" href="?page=contact" aria-expanded="false">
           Contact
          </a>
        </li>

        <li class="nav-item">
        <?php if(isset($_SESSION['user'])):?>
          <a class="nav-link" href="?page=logout">Logout</a>
        <?php  else: ?>
          <a class="nav-link" href="?page=login">Login</a>
        <?php  endif ?>
        </li>
            <!-- <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Account
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <?php if(isset($_SESSION['user'])):?>
            <li><a class="dropdown-item" href="?page=login">Login</a></li>
            <?php  else: ?>
            <li><a class="dropdown-item" href="?page=logout">Logout</a></li>
            <?php  endif ?>
            <li><a class="dropdown-item" href="?page=home">Home</a></li>
            <li><a class="dropdown-item" href="?page=gallery">Gallery</a></li>
            <li><a class="dropdown-item" href="?page=shop">Shop</a></li>
            <li><a class="dropdown-item" href="?page=contact">Contact</a></li>
          </ul>
        </li> -->

      </ul>
      <form class="d-flex" >
        <input name="page" value="search" type="hidden">
        <input name="keywords" class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>

    </div>
  </div>
</nav>

</header>
<!-- MAIN -->
<main class="container-fluid">
<?php include "./views/template_".$page.".phtml" ?>
</main>
<!-- FOOTER -->
<footer class="footer">
    <p>&copy; CCI BEAUJOLAIS - DWWM</p>
</footer>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js
"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.js"></script>
</body>
</html>